name: Build Project

on:
  push:
    branches: [ experimental ]
  pull_request:
    branches: [ experimental ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Setup the workspace
        run: ./gradlew setupCIWorkspace
      - name: Build with Gradle
        run: ./gradlew build

  test-scala-presence:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check
        uses: mattsb42-meta/not-grep@1.0.0
        with:
          config-file: ./.github/test-scala-presence.toml